app:
  http_port: 8888
  auth:
    secret_key: ""
    signing_key: ""
    ttl: 1
    requirements:
      min_length:
        password: 8
        username: 1
      number_of:
        upper_case: 1
        lower_case: 1
        digits: 1
    ldap:
      server: "localhost:389"
      filterDN: "(&(objectClass=person)(|(sAMAccountName={username})(mail={username})))"
      baseDN: "OU={},DC={},DC={}"
  log:
    dir: "logs"
    file: "app.log"
  db:
    login: ""
    pass: ""
    host: ""
    port: "3106"
    name: ""
    args: "parseTime=true&multiStatements=true"
